[package]
org = "dz"
name = "ai_gateway"
version = "1.2.0"
distribution = "2201.11.0"
authors = ["Chintana Wilamuna"]
license = ["Apache-2.0"]
repository = "https://github.com/wx-yz/ai-gateway"

[build-options]
observabilityIncluded = true
