# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ai_gateway_pb2 as ai__gateway__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ai_gateway_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AIGatewayStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ChatCompletion = channel.unary_unary(
                '/ai_gateway.AIGateway/ChatCompletion',
                request_serializer=ai__gateway__pb2.ChatCompletionRequest.SerializeToString,
                response_deserializer=ai__gateway__pb2.ChatCompletionResponse.FromString,
                _registered_method=True)


class AIGatewayServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ChatCompletion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIGatewayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ChatCompletion': grpc.unary_unary_rpc_method_handler(
                    servicer.ChatCompletion,
                    request_deserializer=ai__gateway__pb2.ChatCompletionRequest.FromString,
                    response_serializer=ai__gateway__pb2.ChatCompletionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai_gateway.AIGateway', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai_gateway.AIGateway', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIGateway(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ChatCompletion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_gateway.AIGateway/ChatCompletion',
            ai__gateway__pb2.ChatCompletionRequest.SerializeToString,
            ai__gateway__pb2.ChatCompletionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
