# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai_gateway.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'ai_gateway.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61i_gateway.proto\x12\nai_gateway\"}\n\x15\x43hatCompletionRequest\x12\x14\n\x0cllm_provider\x18\x01 \x01(\t\x12%\n\x08messages\x18\x02 \x03(\x0b\x32\x13.ai_gateway.Message\x12\x13\n\x0btemperature\x18\x03 \x01(\x02\x12\x12\n\nmax_tokens\x18\x04 \x01(\x05\"(\n\x07Message\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"\x9b\x01\n\x16\x43hatCompletionResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06object\x18\x02 \x01(\t\x12\x0f\n\x07\x63reated\x18\x03 \x01(\x03\x12\r\n\x05model\x18\x04 \x01(\t\x12#\n\x07\x63hoices\x18\x05 \x03(\x0b\x32\x12.ai_gateway.Choice\x12 \n\x05usage\x18\x06 \x01(\x0b\x32\x11.ai_gateway.Usage\"T\n\x06\x43hoice\x12\r\n\x05index\x18\x01 \x01(\x05\x12$\n\x07message\x18\x02 \x01(\x0b\x32\x13.ai_gateway.Message\x12\x15\n\rfinish_reason\x18\x03 \x01(\t\"O\n\x05Usage\x12\x15\n\rprompt_tokens\x18\x01 \x01(\x05\x12\x19\n\x11\x63ompletion_tokens\x18\x02 \x01(\x05\x12\x14\n\x0ctotal_tokens\x18\x03 \x01(\x05\x32\x64\n\tAIGateway\x12W\n\x0e\x43hatCompletion\x12!.ai_gateway.ChatCompletionRequest\x1a\".ai_gateway.ChatCompletionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_gateway_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHATCOMPLETIONREQUEST']._serialized_start=32
  _globals['_CHATCOMPLETIONREQUEST']._serialized_end=157
  _globals['_MESSAGE']._serialized_start=159
  _globals['_MESSAGE']._serialized_end=199
  _globals['_CHATCOMPLETIONRESPONSE']._serialized_start=202
  _globals['_CHATCOMPLETIONRESPONSE']._serialized_end=357
  _globals['_CHOICE']._serialized_start=359
  _globals['_CHOICE']._serialized_end=443
  _globals['_USAGE']._serialized_start=445
  _globals['_USAGE']._serialized_end=524
  _globals['_AIGATEWAY']._serialized_start=526
  _globals['_AIGATEWAY']._serialized_end=626
# @@protoc_insertion_point(module_scope)
